apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudops.fullname" . }}-secrets
  labels:
    {{- include "cloudops.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.backend.secrets.secretKey | quote }}
  POSTGRES_USER: {{ .Values.backend.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.backend.secrets.postgresPassword | quote }}
