apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bittush8789/cloudops-control-center.git
    targetRevision: main
    path: gitops-repo/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
