apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudops-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: cloudops-project
  source:
    repoURL: https://github.com/bittush8789/cloudops-control-center.git
    targetRevision: main
    path: gitops-repo/helm
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
