apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloudops-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  description: Project for CloudOps Control Center
  sourceRepos:
    - '*'
  destinations:
    - namespace: cloudops-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
