apiVersion: v1
kind: Secret
metadata:
  name: cloudops-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  url: https://github.com/bittush8789/cloudops-control-center.git
  username: bittush8789
  password: YOUR_GITHUB_TOKEN
